global:
  # No global SMTP configuration - using webhooks only for testing

# The directory from which notification templates are read.
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# The root route on which each incoming alert enters.
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      service: mysql
    receiver: 'database-alerts'
  - match:
      service: nginx
    receiver: 'web-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/'
        send_resolved: true
        
  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/critical'
        send_resolved: true
        
  - name: 'database-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/database'
        send_resolved: true
        
  - name: 'web-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/web'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
