version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}
  mysql_data: {}
  k6_data: {}
  alertmanager_data: {}

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--alertmanager.notification-queue-capacity=10000'
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - alertmanager

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
      - '--cluster.advertise-address=0.0.0.0:9093'
    ports:
      - "9093:9093"
    networks:
      - monitoring

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sample_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - monitoring

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    restart: unless-stopped
    environment:
      - DATA_SOURCE_NAME=mysqluser:mysqlpassword@(mysql:3306)/
    volumes:
      - ./mysqld-exporter:/etc/mysqld-exporter
    command:
      - '--config.my-cnf=/etc/mysqld-exporter/config.cnf'
      - '--collect.info_schema.tables'
      - '--collect.info_schema.innodb_metrics'
      - '--collect.global_status'
      - '--collect.global_variables'
    depends_on:
      - mysql
    ports:
      - "9104:9104"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/mysql-dashboard.json:/var/lib/grafana/dashboards/mysql-dashboard.json
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - monitoring

  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    restart: unless-stopped
    command: >
      bash -c "apt-get update &&
               apt-get install -y curl wget gnupg2 lsb-release &&
               wget -q -O - https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz | tar xzf - -C /tmp &&
               cp /tmp/node_exporter-1.6.1.linux-amd64/node_exporter /usr/local/bin/ &&
               /usr/local/bin/node_exporter"
    ports:
      - "9101:9100" # Node exporter (for monitoring)
    networks:
      - monitoring
    depends_on:
      - prometheus

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx-html:/usr/share/nginx/html
      - ./nginx-config:/etc/nginx/conf.d
    ports:
      - "8080:80"  # Nginx web server
    networks:
      - monitoring
    depends_on:
      - prometheus

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    restart: unless-stopped
    command: -nginx.scrape-uri=http://nginx:80/stub_status
    ports:
      - "9113:9113"  # Nginx exporter metrics port
    networks:
      - monitoring
    depends_on:
      - nginx
      
  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./k6-scripts:/scripts
      - k6_data:/data
    networks:
      - monitoring
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    depends_on:
      - nginx
      - influxdb
      
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    networks:
      - monitoring