global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
      
  - job_name: 'ubuntu'
    static_configs:
      - targets: ['ubuntu:9100']
      
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
